### ISSUE TITLE
JSONDecodeError error on script start

### ISSUE THREAD

**Issue by Sebster7** [Suncatcher/aws_sg_migrate#4]
So, whether I try with or without the parameters, I get this traceback:

> $ python3.8 ./aws_sg_migrate.py
> Traceback (most recent call last):
>   File "./aws_sg_migrate.py", line 7, in <module>
>     data = json.loads(ap.decode('utf-8'))
>   File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Suncatcher** [comment]
Hi, thanks for testing.
I just checked and all works like a charm. Maybe you have some non-printable character in Bash prompt?

**Comment by Sebster7** [comment]
I don't think so.  Do you mean in my bash prompt or in my bash command?  Did you test on python3.8?  It's been a long time since I opened this issue, so I can't remember what system I tested it on sadly.

**Comment by Suncatcher** [comment]
Sorry I meant in CMD on the step of Bash script generation.
I just tested it on Python 3.10 in Windows Terminal, it works fine.

**Comment by nix-power** [comment]
```
cmd = [ 'aws', 'ec2', 'describe-regions' ]
 ap = subprocess.check_output(cmd)
 data = json.loads(ap.decode('utf-8'))

``` 

 i think you should check your settings inside ~/.aws
 then verify with aws cli
 aws ec2 describe-regions
 as it looks like this command returns an empty result for you. 
 Script works fine
